// routes/[event]/submissions.tsx
import { RouteContext } from "$fresh/server.ts";

import { fetchEvent, fetchEventSubmissions, fetchUser } from "../../lib/platform-api.tsx";
import { formatPlural, getLink } from "../../lib/helpers.tsx";
import { Submission } from "../../lib/types.d.tsx";

export default async function Submissions(_req: Request, ctx: RouteContext) {
  const event = await fetchEvent(fetch, ctx.params.event);
  const submissions = await fetchEventSubmissions(fetch, ctx.params.event);
  submissions.sort((a,b) => a?.name?.localeCompare(b?.name));
  // Fetch user data of all authors
  const users = (await Promise.all([...new Set(submissions.flatMap(s => s.authors))].map(author => fetchUser(fetch, author))))
  const participants = new Set<string>();

  if (submissions) {
    submissions.forEach((submissions: Submission) => {
      submissions.authors.forEach((author) => participants.add(author));
    });
  }
  
  return (
    <div
      class="flex flex-col gap-4 mb-16"
      style={`--color-mf-link: #${event.colors.primary}; --color-mf-event-background: #${event.colors.secondary}`}
    >
      <a
        href={`/${event.id}`}
        class="card flex flex-row gap-4 clickable"
        style="background-color: #{event.colors.secondary}"
      >
        <div class="icon">
          <img
            alt={`Transparent icon for to ${event.name}`}
            class="h-16"
            src={event.images.transparent}
          />
        </div>
        <div>
          <h1>{event.name}</h1>
          <p>
            {`${event.name} ${
              event.phase !== "modding" ? "has" : "had"
            } a total of ${
              formatPlural("submission", submissions.length)
            } created by ${
              formatPlural(
                "modder",
                participants.size,
              )
            } ${event.phase === "modding" ? " so far" : ""}.`}
          </p>
        </div>
      </a>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {submissions.map((submission: Submission, submissionIndex) => (
          <div
            class="shadow-(--shadow-mf-card) rounded-2xl bg-mf-card overflow-hidden text-[unset] clickable"
            key={submissionIndex}
            target="_blank"
          >
            <a href={getLink(submission)} target="_blank">
              <div class="w-full bg-mf-unknown h-40 overflow-hidden z-[5]">
                {submission.images && submission.images.screenshot && (
                  <img
                    class="w-full h-40 object-cover"
                    src={submission.images.screenshot}
                    alt="Gallery image for {submission.name}"
                  />
                )}
              </div>
            </a>
            <div class="p-4 pt-3 self-center">
              {submission.images && submission.images.icon && (
                <a href={getLink(submission)} target="_blank">
                  <div class="w-24 h-24 object-contain rounded-2xl border-mf-card border-4 border-solid mt-[-4rem] bg-mf-unknown overflow-hidden z-10 absolute">
                    <img
                      class="w-24 h-24 pixelated"
                      src={submission.images.icon}
                      alt="Icon for {submission.name}"
                    />
                  </div>
                </a>
              )}
              <div
                class={submission.images && submission.images.icon
                  ? "ml-[7.25rem]"
                  : ""}
              >
                <a
                  href={getLink(submission)}
                  target="_blank"
                  style="text-decoration:none"
                >
                  <h3 class="m-0 text-mf-heading">{submission.name}</h3>
                </a>
                {submission.authors.map((author, index) => {
                  const user = users.find((u) => u.id === author);
                  return user
                    ? (
                      <a
                        key={`${submissionIndex}-${index}`}
                        href={`/user/${user.id}`}
                      >
                        {user.name}
                      </a>
                    )
                    : author;
                }).map((userElement, index) => {
                  let join = "";
                  if (index === submission.authors.length - 1) {
                    if (
                      submission.authors.length > 2
                    ) {
                      join = ", and ";
                    } else if (
                      submission.authors.length === 2
                    ) {
                      join = " and ";
                    }
                  } else if (index > 0) {
                    join = ", ";
                  }
                  return (
                    <span key={`${submissionIndex}-${index}`}>
                      <span>{join}</span>
                      {userElement}
                    </span>
                  );
                })}
              </div>
              <p className="m-0 mt-2 text-mf-heading">
                {submission.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/routes/[event]/submissions.svelte
<script context="module" lang="ts">
	export const load: import('./__types/__layout').Load = async ({ params, fetch }) => {
		let event: any;
		await fetch('https://platform.modfest.net/event/' + params.event)
			.then((response) => response.json())
			.then((data) => {
				event = data;
			})
			.catch((error) => {
				console.log(error);
				return null;
			});

		if (event === null) {
			return {
				status: 404
			};
		}

		let submissions: any;
		await fetch('https://platform.modfest.net/submissions')
			.then((response) => response.json())
			.then((data) => {
				submissions = data;
			})
			.catch((error) => {
				console.log(error);
				return [];
			});

		let users: any;
		await fetch('https://platform.modfest.net/users?map')
			.then((response) => response.json())
			.then((data) => {
				users = data;
			})
			.catch((error) => {
				console.log(error);
				return [];
			});

		if (submissions.length > 0) {
			return {
				props: {
					event,
					submissions,
					users
				},
				stuff: {
					event,
					submissions,
					users
				}
			};
		}

		return {
			status: 404
		};
	};
</script>

<script lang="ts">
	function compareSubmission(a: any, b: any) {
		const aName = a.name.toLowerCase().replace(/[^a-z0-9]/gi, '');
		const bName = b.name.toLowerCase().replace(/[^a-z0-9]/gi, '');
		if (aName < bName) {
			return -1;
		}
		if (aName > bName) {
			return 1;
		}
		return 0;
	}

	export let event: any;
	export let submissions: any[];
	export let users: any;

	submissions.sort(compareSubmission);
	const modders = [...new Set(submissions.map((submission: any) => submission.members).flat())];
	submissions.forEach((s) => {
		s.authors = [];
		s.members.forEach((m: string) => {
			s.authors.push(users[m]);
		});
	});
</script>

<a href="/{event.id}" class="card clickable" style="background-color: {event.background_color}">
	<div class="icon">
		{@html event.logo}
	</div>
	<div class="content">
		<h1>{event.name}</h1>
		<p>
			ModFest: Singularity had a total of {submissions.length} submissions created by {modders.length}
			total modders.
		</p>
	</div>
</a>
<div class="submissions">
	{#each submissions as submission}
		<a class="submission clickable" href="{submission.modrinth_url}" target="_blank">
			<div class="header">
				{#if submission.gallery_url}
					<img
						class="banner"
						src={submission.gallery_url}
						alt="Gallery image for {submission.name}"
					/>
				{/if}
			</div>
			<div class="content {submission.icon_url ? 'has-icon' : ''}">
				{#if submission.icon_url}
					<div class="icon">
						<img src={submission.icon_url} alt="Icon for {submission.name}" />
					</div>
				{/if}
				<div class="title">
					<h3>{submission.name}</h3>
					by
					{#each submission.authors as author, index}
						{#if submission.authors.length > 1 && index === submission.authors.length - 1},&nbsp;and&nbsp;{:else if submission.authors.length > 2 && index < submission.authors.length - 1 && index !== 0},&nbsp{/if}{author.display_name}
					{/each}
				</div>
				<p>{submission.summary}</p>
			</div>
		</a>
	{/each}
</div>

<style>
	.submissions {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 1rem;
	}

	@media only screen and (max-width: 600px) {
		.submissions {
			grid-template-columns: repeat(1, 1fr);
		}
	}

	.card {
		display: flex;
		flex-direction: row;
		gap: 1rem;
	}

	.card .icon :global(svg) {
		height: 4rem;
	}

	.card .content {
		align-self: center;
	}

	.submission {
		box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1);
		border-radius: 1rem;
		background-color: var(--card-color);
		overflow: hidden;
		color: unset;
	}

	.submission .content {
		padding: 1rem;
		padding-top: 0.75rem;
	}

	.submission .content h3 {
		margin: 0;
		color: var(--heading-color);
	}

	.submission .content p {
		margin: 0;
		margin-top: 0.5rem;
		color: var(--heading-color);
	}

	.submission .header {
		width: 100%;
		background-color: var(--unknown-color);
		height: 10rem;
		overflow: hidden;
		z-index: 5;
	}

	.submission .header .banner {
		width: 100%;
		height: 10rem;
		object-fit: cover;
	}

	.submission .icon {
		width: 6rem;
		height: 6rem;
		object-fit: contain;
		border-radius: 1rem;
		border: 0.25rem solid var(--card-color);
		margin-top: -4rem;
		background-color: var(--unknown-color);
		overflow: hidden;
		z-index: 10;
		position: absolute;
	}

	.submission .icon img {
		width: 6rem;
		max-height: 6rem;
	}

	.submission .has-icon .title {
		margin-left: 7.25rem;
	}
</style>
